project:
  type: website
  output-dir: docs

website:
  title: "PM566 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: About this site
      - href: Final Project Report.html
        text: Download the Report
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

